# Generated by Django 4.2.11 on 2024-04-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_birdhouse_alter_feeding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='birdhouses',
            field=models.ManyToManyField(to='main_app.birdhouse'),
        ),
    ]
